#--------------------------------------------------------------------------------------
# This GitHub Actions workflow can be run locally using https://github.com/nektos/act
#
# act normally uses docker, but it can also be run using podman on Fedora 37:
# dnf install act-cli podman-docker
# podman system service -t 0 &
# act --bind --container-daemon-socket $XDG_RUNTIME_DIR/podman/podman.sock -W .github/workflows/main.yml
#--------------------------------------------------------------------------------------
name: Dom0 Tests
on:
  # push:
  issue_comment:
    types: [created, edited]
  # if: ${{ startsWith(github.event.comment.body, '/run dom0 tests') }}
  # if: true
  #- if: ${{ startsWith(github.event.comment.body, '/push-container') && github.event.issue.pull_request && matches(github.event.comment.body, '/push-container.*') }}
  # - types: [created]
  # pull_request_target:
  #  types:
  #    - opened
  # pull_request:
  #  types: [created]
  # issue_comment:
  #  types: [created, edited]
  #  if: ${{ startsWith(github.event.comment.body, '/push-container') && github.event.issue.pull_request && matches(github.event.comment.body, '/push-container.*') }}
# env:
#  ACTIONS_RUNNER_HOOK_JOB_COMPLETED: /bin/true

jobs:
  pr_commented:
    name: Run tests for /run dom0 tests
    if: ${{ github.actor == 'bernhardkaindl' }}
    # && startsWith(github.event.comment.body, '/run dom0 tests') }}
    runs-on: Dom0  # self-hosted runners with label: Dom0
      # github.event.pull_request.label.name == 'dom0test' ||
      # github.event.pull_request.label.name == 'dom0test'
    ##if: ${{ github.event.issue.pull_request }}
    steps:
    - uses: actions/checkout@v3
    - name: Test xen-bugtool -s --entries=persistent-stats to check getting RRDs of VMs
      run: |
        set -xv
        echo ${{ github.event.comment.body }}
        echo ${{ github.event.comment.user.login }}
        echo ${{ github.actor }}
        echo ${{ github.event.comment.html_url }}
        echo "$GITHUB_CONTEXT"
        python2 xen-bugtool --help
        python2 xen-bugtool --capabilities
        sudo python2 xen-bugtool -s --entries=persistent-stats --output=tar -y --outfd=1 >bugtool.tar
        tar xvf bugtool.tar --strip-components=1
        find * -type f -print0 | xargs -0 ls -l
        dom0label="Control domain on host: $HOSTNAME"
        uuid=`xe vm-list params=uuid name-label="$dom0label" --minimal`
        file xapi_rrd-$uuid.out
        xmllint xapi_rrd-$uuid.out >/dev/null
    - name: 'Comment on PR'
      uses: actions/github-script@v6
      with:
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              issue_number:  context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Testing in Dom0 completed successfully'
            });